{"name": "Невозможно авторизовать пользователя, если хотя бы одно из полей неверно", "status": "passed", "parameters": [{"name": "field", "value": "'password'"}], "start": 1719127735943, "stop": 1719127737479, "uuid": "69b95b00-8652-4ace-8008-bcf5c88effcd", "historyId": "8937fff3295554d9ec4def257483dc0c", "testCaseId": "75e5e0134f47bb9cc437e9df45383da3", "fullName": "tests.test_user.TestUserLogin#test_user_login_with_wrong_data_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "thinkpad"}, {"name": "thread", "value": "9864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}