{"name": "Невозможно создать пользователя если данные уже используются", "status": "passed", "start": 1719127729216, "stop": 1719127731646, "uuid": "8c1d72c1-daf3-4a74-8c0d-de9908427ff8", "historyId": "0bc436b64235fc72cee575efbd5870e3", "testCaseId": "0bc436b64235fc72cee575efbd5870e3", "fullName": "tests.test_user.TestUserCreation#test_create_already_existed_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "thinkpad"}, {"name": "thread", "value": "9864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}